[package]
name = "cryptoki-sys"
version = "0.1.6"
authors = ["Contributors to the Parsec project"]
edition = '2018'
description = "FFI wrapper around the PKCS #11 API"
readme = "README.md"
keywords = ["pkcs11", "cryptoki", "hsm"]
categories = ["api-bindings", "external-ffi-bindings", "cryptography", "hardware-support"]
license = "Apache-2.0"
repository = "https://github.com/parallaxsecond/rust-cryptoki"
documentation = "https://docs.rs/crate/cryptoki-sys"

[build-dependencies]
bindgen = { version = "0.63.0", optional = true }
target-lexicon = "0.12.0"

[dependencies]
libloading = "0.7.0"

[features]
generate-bindings = ["bindgen"]
